"""Generate a container-orchestrator profile from the same synthetic spec the lab reads.

    python tools/compose_profile.py --instance scenarios/S01/input/instance --out compose/S01-valdora.compose.yaml

The profile is an illustration of how the topology of an instance would be written for a
container orchestrator: services, networks, restart policies, healthchecks. It is **generated
and never executed**: no test, no scenario and no CI job starts a container, and nothing in the
pack depends on it. Image references are placeholders under a reserved name with the digest
left ``[TO CONFIRM]``; routing stays in the ``routes/`` files (file provider), so the profile
carries no routing labels and mounts no orchestrator socket.
"""
from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from lab import jsonio, topology  # noqa: E402

_RESTART = {"always": "always", "on-failure": "on-failure", "unless-stopped": "unless-stopped", "no": "no"}


def render(topo: topology.Topology, instance_id: str) -> str:
    lines = [
        "# GENERATED by tools/compose_profile.py - illustration only, never executed by tests, scenarios or CI.",
        f"# Source: synthetic instance {instance_id} ({topo.company}, fictitious). Images are placeholders.",
        "name: " + instance_id.lower(),
        "services:",
    ]
    for name in sorted(topo.services):
        svc = topo.services[name]
        lines += [f"  {name}:",
                  f"    image: \"registry.example/{name}@sha256:[TO CONFIRM]\"",
                  f"    restart: \"{_RESTART.get(svc.restart_policy, 'no')}\"",
                  "    expose:",
                  f"      - \"{svc.port}\"",
                  "    networks:"]
        lines += [f"      - {net}" for net in svc.networks]
        if svc.health_kind == "http":
            lines += ["    healthcheck:",
                      f"      test: [\"CMD\", \"wget\", \"-q\", \"-O\", \"/dev/null\", \"http://127.0.0.1:{svc.port}{svc.health_path}\"]",
                      "      interval: 60s",
                      "      retries: 2"]
        else:
            lines += ["    # healthcheck of kind 'process': the orchestrator only knows that the process is up.",
                      "    # The lab's end-to-end probe exists because this is not enough (see scenario S04)."]
    lines.append("networks:")
    for net in sorted(topo.networks):
        lines.append(f"  {net}:")
        if topo.networks[net] == "internal":
            lines.append("    internal: true")
        else:
            lines.append(f"    # plane: {topo.networks[net]}")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--instance", required=True, help="instance directory with instance.json and topology.yaml")
    ap.add_argument("--out", required=True, help="file to write")
    args = ap.parse_args(argv)
    topo, problems = topology.load(args.instance)
    if topo is None:
        print("topology unreadable: " + "; ".join(problems))
        return 2
    instance_id = str(jsonio.read(os.path.join(args.instance, "instance.json"))["instance_id"])
    jsonio.write_text(args.out, render(topo, instance_id))
    print(f"written: {args.out} ({len(topo.services)} services, {len(topo.networks)} networks) - not executed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
